<a href="https://colab.research.google.com/github/minhbao1705/pytorch_tutorial/blob/main/Tensor_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Giới thiệu pytorch

Pytorch là một thư viện của Python được dùng để xây dựng mô hình AI. Với sự linh hoạt và cho phép các mô hình học sâu được dễ dàng xây dựng từ python - Pytorch được phát triển bởi nhóm nghiên cứu hàng đầu của facebook đang ngày càng được sử dụng nhiều trong giới nghiên cứu và phát triển các sản phẩm AI. Pytorch cho phép khả năng tăng tốc phần cứng dựa trên GPU qua đó hỗ trợ rất nhiều trong việc huấn luyện mô hình.

## a. Một số đặc trưng của Pytorch
Dưới đây là một vài những thuộc tính quan trọng giúp cho pytorch ngày càng được thịnh hành hơn.
- **Easy Interface**: Pytorch cung cấp API để sử dụng - vì vậy việc triển khải và thực thi code với framework trở nên dễ dàng hơn.
- **Python Usage**: Bên cạnh việc hỗ trợ mạnh mẽ cho AI, DS thì pytorch có thể tận dụng tất cả các dịch vụ, chức năng và môi trường được cung cấp bởi Python.
- **Computational Graph**: Pytorch cung cấp các đồ thị tính toán động (dynamic computational graphs) - do đó người dùng có thể thay đổi chúng trong thời gian thực thi.

## b. Một số tiện ích của Pytorch 
Một số tiện ích khi làm việc với Pytorch:
- Dễ dàng hiểu và debug code.
- Pytorch như một phần mở rộng của Numpy khi hỗ trợ việc tính toán trên GPU.
- Dễ dàng xây dựng triển khai kiến trúc mạng.

# 2. Tensor

## I - Giới thiệu tensor
Tensor là một kiểu dữ liệu cho phép lưu trữ dữ liệu với số chiều tùy ý, dữ liệu lưu trữ này có thể là một giá trí vô hướng, vector, mảng 1 chiều, mảng 2 chiều hay mảng n chiều.
VD: 
- Giá trí vô hướng: 100
- Vector: [1, 2, 3]
- Mảng 2 chiều: [[1, 2, 3], [2, 3, 4]]
- Mảng n chiều (n=3): [[[1, 2], [2, 3]]]

In [1]:
import torch

scalar = torch.empty(1)
print("scalar: ", scalar)
vector = torch.zeros(3)
print("vector: ", vector)
matrix2D = torch.ones(2, 3)
print("matrix2D: ", matrix2D)
matrix3D = torch.rand(2, 2, 3)
print("matrix3D: ", matrix3D)

scalar:  tensor([5.6766e+27])
vector:  tensor([0., 0., 0.])
matrix2D:  tensor([[1., 1., 1.],
        [1., 1., 1.]])
matrix3D:  tensor([[[0.1953, 0.8326, 0.6490],
         [0.3934, 0.3118, 0.3393]],

        [[0.3484, 0.8730, 0.3108],
         [0.6762, 0.1734, 0.9980]]])


In [2]:
# check size
matrix2D.size()

torch.Size([2, 3])

In [3]:
# check data type
matrix3D.dtype

torch.float32

In [4]:
# specify types, float32 default
x = torch.zeros(2, 2, dtype=torch.float16)
print(x)

tensor([[0., 0.],
        [0., 0.]], dtype=torch.float16)


In [5]:
# construct from data
x = torch.tensor([5.5, 3])
print(x.size())
print(x)

torch.Size([2])
tensor([5.5000, 3.0000])


## II - requires_grad_argument

Tham số này cho biết tensor cần được tính đạo hàm - đây là một bước quan trọng trong quá trình training model.

In [6]:
x = torch.tensor([6., 9.], requires_grad=True)
print(x)

tensor([6., 9.], requires_grad=True)


## III - Một số phép toán trong tensor

In [7]:
x = torch.rand(3, 3)
y = torch.rand(3, 3)

In [9]:
# elementwise addition
z = x + y
_z = torch.add(x, y)
print(z)
print(_z)

tensor([[1.5613, 0.9238, 0.1394],
        [0.6728, 1.0922, 0.3278],
        [0.1665, 1.4842, 1.0978]])
tensor([[1.5613, 0.9238, 0.1394],
        [0.6728, 1.0922, 0.3278],
        [0.1665, 1.4842, 1.0978]])


In [10]:
# suntraction
z = x - y
_z = torch.sub(x, y)
print(z)
print(_z)

tensor([[-0.3937, -0.5635,  0.0816],
        [-0.4842, -0.3620, -0.2451],
        [-0.0323,  0.1695,  0.8260]])
tensor([[-0.3937, -0.5635,  0.0816],
        [-0.4842, -0.3620, -0.2451],
        [-0.0323,  0.1695,  0.8260]])


In [11]:
# mutiplication
z = x * y
_z = torch.mul(x, y)
print(z)
print(_z)

tensor([[0.5707, 0.1340, 0.0032],
        [0.0546, 0.2655, 0.0119],
        [0.0067, 0.5435, 0.1307]])
tensor([[0.5707, 0.1340, 0.0032],
        [0.0546, 0.2655, 0.0119],
        [0.0067, 0.5435, 0.1307]])


In [12]:
# division
z = x / y
_z = torch.div(x, y)
print(z)
print(_z)

tensor([[0.5973, 0.2423, 3.8210],
        [0.1630, 0.5021, 0.1445],
        [0.6754, 1.2579, 7.0798]])
tensor([[0.5973, 0.2423, 3.8210],
        [0.1630, 0.5021, 0.1445],
        [0.6754, 1.2579, 7.0798]])


## IV - Slicing

In [13]:
x = torch.rand(3, 5)
print(x)

tensor([[0.5070, 0.3083, 0.3087, 0.5748, 0.7191],
        [0.1583, 0.2155, 0.1802, 0.3515, 0.9752],
        [0.6955, 0.1142, 0.9946, 0.8586, 0.4828]])


In [14]:
# all rows, column 0
print(x[:, 0])

tensor([0.5070, 0.1583, 0.6955])


In [15]:
# row 1, all column
print(x[1, :])

tensor([0.1583, 0.2155, 0.1802, 0.3515, 0.9752])


In [16]:
# get element at 1,1
print(x[1, 1])

tensor(0.2155)


Lấy giá trị thực của (sử dụng khi chỉ có 1 phần tử trong tensor)

In [17]:
print(x[1, 1].item())

0.21547359228134155


## V - Reshape

In [19]:
x = torch.rand(4, 4)

In [20]:
y = x.view(16)
print(y)
print(y.size())

tensor([0.5223, 0.1095, 0.4484, 0.9745, 0.7486, 0.6275, 0.8312, 0.4636, 0.3319,
        0.3699, 0.6107, 0.5699, 0.8057, 0.4325, 0.5523, 0.0466])
torch.Size([16])


Sử dụng -1 để suy ra chiều mới từ số chiều hiện tại với -1 pytorch sẽ tự động quyết định size cần thiết

In [22]:
y = x.view(-1, 8)
print(y)
print(y.size())

tensor([[0.5223, 0.1095, 0.4484, 0.9745, 0.7486, 0.6275, 0.8312, 0.4636],
        [0.3319, 0.3699, 0.6107, 0.5699, 0.8057, 0.4325, 0.5523, 0.0466]])
torch.Size([2, 8])


## VI - Pytorch và Numpy

In [23]:
# torch to numpy
a = torch.ones(3)
print(a)
print(type(a))
b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1.])
<class 'torch.Tensor'>
[1. 1. 1.]
<class 'numpy.ndarray'>


Lưu ý: nếu tensor đang được chạy trên cpu, cả 2 object đều chia sẻ cùng một memory location, vì vậy khi thay đổi một object thì object còn lại cũng sẽ được thay đổi bằng cú pháp sau

In [25]:
a.add(1)
print(a)
print(b)

tensor([1., 1., 1.])
[1. 1. 1.]


In [26]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2.])
[2. 2. 2.]


In [27]:
# numpy to torch
import numpy as np
a = np.ones(6)
b = torch.from_numpy(a)
print(a)
print(type(a))
print(b)
print(type(b))

[1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>


Tương tự như cách torch chuyển sang numpy. Thì numpy chuyển sang torch cũng v

In [28]:
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2., 2.], dtype=torch.float64)


# VII - Check and config device

In [29]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cpu


## VIII - Move Tensors to GPU

Để sử dụng GPU tính toán các giá trị tensor ta sử dụng cách sau:

In [31]:
x = torch.ones(5)
if torch.cuda.is_available():
  device = torch.device("cuda")
  y = torch.ones(5, device=device)
  z = x.to(device)
  z = x + y
  print(z)

Lưu ý rằng numpy không chạy được trên GPU vì vậy muốn chuyển torch sang numpy thì phải set device lại thành cpu rồi mới thực hiện bước chuyển.